### ISSUE TITLE
Crash on 0.18.0 with blank screen

### ISSUE THREAD

**Issue by gandalff512** [victorbalssa/abacus#311] opened 2024-07-07 08:34 UTC
hello friend! In the new version 0.18.0 for android, there is a white screen after authorization. The version of my firefly-iii is 6.1.18. I tried resetting the application settings, but it didn't help. My phone is Samsung S23

**Comment by SimonAkers** [comment] 2024-07-07 23:48
I'm having the same issue, using a Samsung Galaxy S22+. FF3 v6.1.18 (latest).

I first noticed the issue a couple weeks ago after it starting saying "New update available!" in the app itself. Clicking "yes" to update would cause this issue regardless of if I cleared app data and setup credentials again. After authorization, you get a white screen and cannot use the app.

For a while, I was able to get past it by clicking "cancel" on the update notification (after resetting the app data), but now with the latest version of the app being pushed to the Google Play store on July 4th, there's no notification that pops up or workaround I've found.

Let me know if I can be of any extra help, would love to see this fixed so I can keep using the app!

**Comment by victorbalssa** [comment] 2024-07-08 12:28
Hey!

I'm trying to replicate this locally, it's working smoothly for me on my Android.

Do you have any special configurations on how you access your Firefly III instance?

Can you try to connect to https://demo.firefly-iii.org/ with OAuth to see if it comes from FIII or Abacus?

Thanks!

**Comment by SimonAkers** [comment] 2024-07-08 13:11
I've just tried it out with the demo version and it works fine. I'll have to do some digging after work today to see if I can find anything weird with my configuration, to my knowledge it's fairly standard. It's running in Docker behind NGINX with HTTPS, it could be something I need to update with NGINX if something in FIII changed. Any thoughts?

**Comment by victorbalssa** [comment] 2024-07-08 13:24
> With HTTPS

Do you have custom local certificates on your android?

**Comment by gandalff512** [comment] 2024-07-08 15:16
I have through https://demo .firefly-iii.org / with OAuth, everything works too. 

In my configuration, I also use Docker, an HTTP connection

<img width="203" alt="image" src="https://github.com/victorbalssa/abacus/assets/81572829/e6087d23-e3a3-4ba1-bf79-be39d5331c61">

**Comment by gandalff512** [comment] 2024-07-08 15:17
All settings are standard, I tried to connect via OAuth and Personal Access Tokens

**Comment by SimonAkers** [comment] 2024-07-09 00:38
> > With HTTPS
> 
> Do you have custom local certificates on your android?

I don't believe so. I had previously manually registered the domain with LetsEncrypt using Certbot. I believe that has expired though, but my domain registrar (Porkbun) now automatically manages a LetsEncrypt cert for the domain on my behalf. There could be something conflicting with the old manual cert I made, but I believe that expired some months ago and the issue is within the last 2-3 weeks. The default Firefly web GUI works fine and reports a secure connection on all my devices, so there's no immediately obvious problems.

If you don't mind my asking @victorbalssa, what brand Android are you using? I know Samsung has a pretty heavily modified version of Android so I am keeping in mind that it could be an isolated issue. Though I'm guessing since the demo worked then it's not an Android problem necessarily (however the demo is on the development branch afaik and I'm running release).

I'll try to look into it closer ASAP and get back to you about it (work keeping me busy lately). I'll want to see if NGINX or Docker has any notable logs.

Thanks for the fast responses! I appreciate your hard work.

**Comment by advait404** [comment] 2024-07-09 13:33
Hi, I am having this same issue.

I am using http connection to my local WiFi device
(http://192.168.101.10:8080)

It gives the white screen issue in both authentication methods (Oauth token and personal access token)

**Comment by igneous80** [comment] 2024-07-10 12:23
Hi, I found same problem both Oauth and personal token.
I've check FFiii docker instance log and everything look fine, no error and server return correct responds.

My phone is Huawei P30 running on official EMUI12 and connect to FFIII docker (6.1.16) via cloudflare tunnel.

**Comment by SimonAkers** [comment] 2024-07-10 12:33
If someone has the time, it could be worth trying a fresh instances of the latest development version. Since it works on the demo version which is in develop branch, it could be something that was fixed recently on Fiii's end. I've been meaning to look at this closer but work has had me slammed all week 🤦

**Comment by igneous80** [comment] 2024-07-10 13:05
> If someone has the time, it could be worth trying a fresh instances of the latest development version. Since it works on the demo version which is in develop branch, it could be something that was fixed recently on Fiii's end. I've been meaning to look at this closer but work has had me slammed all week 🤦

i've tried developer branch Version develop/2024-07-08 but still got white screen.

**Comment by victorbalssa** [comment] 2024-07-10 15:36
> If you don't mind my asking @victorbalssa, what brand Android are you using?

I have a Samsung Galaxy Tab S6 and a OnePlus both are working fine.

I will try to run it on a virtual device with android 14

**Comment by drewzeee** [comment] 2024-07-11 03:33
> I'm having the same issue, using a Samsung Galaxy S22+. FF3 v6.1.18 (latest).
> 
> I first noticed the issue a couple weeks ago after it starting saying "New update available!" in the app itself. Clicking "yes" to update would cause this issue regardless of if I cleared app data and setup credentials again. After authorization, you get a white screen and cannot use the app.
> 
> For a while, I was able to get past it by clicking "cancel" on the update notification (after resetting the app data), but now with the latest version of the app being pushed to the Google Play store on July 4th, there's no notification that pops up or workaround I've found.
> 
> Let me know if I can be of any extra help, would love to see this fixed so I can keep using the app!

I had the exact same experience, except on iOS.

**Comment by victorbalssa** [comment] 2024-07-12 03:16
I'm building a sentry build to catch and get the error message. I will share the apk file for testing.

**Comment by victorbalssa** [comment] 2024-07-12 12:48
It's available here: https://github.com/victorbalssa/abacus/releases/download/0.18.0/abacus-sentry-0.18.2.apk

If someone can try to install this update, I will have access to the error logs and will be able to debug this issue.

Thanks!

**Comment by SimonAkers** [comment] 2024-07-12 16:58
> If someone can try to install this update, I will have access to the error logs and will be able to debug this issue.

Done, I have installed it and tried logging in. You're a legend for the help!

**Comment by victorbalssa** [comment] 2024-07-12 19:03
@SimonAkers for some reasons Sentry SDK wasn't initialize correctly on this version.

I double checked this new version `0.18.2`:  https://github.com/victorbalssa/abacus/releases/download/0.18.0/abacus-sentry-0.18.2.apk and I should work now (at least I should be able to see the error logs).

Thank you for testing this with me!

**Comment by SimonAkers** [comment] 2024-07-12 20:05
@victorbalssa Got it! If it's easier to contact me directly, I have Discord (`shayes`)

**Comment by victorbalssa** [comment] 2024-07-12 20:07
I got it! I will create a patch soon on production release.

**Comment by victorbalssa** [comment] 2024-07-12 21:17
@SimonAkers @drewzeee @igneous80 @advait404 

New `0.19.0` version available directly from OTA update with a fix for this.

**Comment by drewzeee** [comment] 2024-07-12 21:30
> @SimonAkers @drewzeee @igneous80 @advait404 
> 
> 
> 
> New `0.19.0` version available directly from OTA update with a fix for this.

Confirmed working on iOS

**Comment by SimonAkers** [comment] 2024-07-12 21:31
> New `0.19.0` version available directly from OTA update with a fix for this.

Working on my Android! Thank you for the help 😁

**Comment by D4rkT1m0** [comment] 2024-07-13 02:35
Hello guys, how to get the OTA version?

**Comment by D4rkT1m0** [comment] 2024-07-13 03:37
I somehow succeed to update the app as I launched it, the app itself asked me to update which I did. It's working now. 
But when I look in the App Store, the version is still at 18.0

**Comment by SimonAkers** [comment] 2024-07-13 04:00
@D4rkT1m0 OTA means "over the air" and in this context means the update comes from the app directly, instead of from the app store. So the app store won't show the version from the OTA update. It sounds like you did update correctly!

**Comment by D4rkT1m0** [comment] 2024-07-13 04:13
@SimonAkers
> @D4rkT1m0 OTA means "over the air" and in this context means the update comes from the app directly, instead of from the app store. So the app store won't show the version from the OTA update. It sounds like you did update correctly!

Thanks for je fast reply. 
How are we able to launch the OTA update?

Is this something we can interact with? Or do we simply have to wait that the creator make it available from his side?

**Comment by SimonAkers** [comment] 2024-07-13 04:30
> @D4rkT1m0 Is this something we can interact with? Or do we simply have to wait that the creator make it available from his side?

Oops, forgot to explain that, my bad! When an OTA update is available, that's when it says "New update" in the app itself on launch. You can choose "yes" to accept it and update. If I'm not mistaken you can also do it from the settings menu

**Comment by igneous80** [comment] 2024-07-13 04:43
> @SimonAkers @drewzeee @igneous80 @advait404
> 
> New `0.19.0` version available directly from OTA update with a fix for this.

@victorbalssa 
After updated via OTA to 0.19.0, Abacus now back to work!

Thanks!

**Comment by gandalff512** [comment] 2024-07-13 06:59
Thanks guys!

@victorbalssa 
Thank you very much, I also have version 0.19.0 working!

**Closed as completed** 2024-07-15 02:19 UTC
Labels: bug, android, ios

**Comment by DelmorS** [comment] 2025-03-19 11:06
Hello! I have again the same problem with version 0.21 from Googe Play Store. White screen just after login
My firefly is behind a reverse proxy (traefik3), with https
Tried both OAuth and Personal Token
Android 15, Honor Magic 6 Pro
